apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: game-server
  template:
    metadata:
      labels:
        app: game-server
    spec:
      containers:
        - name: game-server
          image: your-registry/game-server:latest
          ports:
            - containerPort: 3000
